## Numpy

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
#craeting ana array

In [5]:
x=np.array([[1,2,3],[4,5,7]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [7]:
np.shape(x)

(2, 3)

In [8]:
np.size(x)

6

In [10]:
np.ndim(x)

2

In [14]:
x.itemsize

4

In [15]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [16]:
#reshape

In [18]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 7]])

In [19]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [7]])

In [20]:
x.reshape(2,2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [21]:
#slicing

In [22]:
x[0]

array([1, 2, 3])

In [27]:
x[0,2]

3

In [30]:
x[1,1]

5

In [31]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [33]:
x[0:,0]

array([1, 4])

In [35]:
x[:,0]

array([1, 4])

In [36]:
x[:,-1]

array([3, 7])

In [37]:
x[:,2]

array([3, 7])

In [45]:
x[:,0::2]

array([[1, 3],
       [4, 7]])

In [46]:
x[:,0:2]

array([[1, 2],
       [4, 5]])

In [50]:
x.min()

1

In [51]:
x.max()

7

In [52]:
x.sum()

22

In [53]:
x.mean()

3.6666666666666665

In [62]:
x.min(0)

array([1, 2, 3])

In [58]:
x.max(axis=1)

array([3, 7])

In [63]:
x.sum(axis=0)

array([ 5,  7, 10])

In [64]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [65]:
x.sum(axis=1)

array([ 6, 16])

In [67]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.64575131]])

In [68]:
np.std(x)

1.9720265943665387

In [69]:
a=np.array([(1,3,5),(3,4,5),(2,8,7)])

In [70]:
b=np.array([(6,3,9),(5,3,8),(9,7,5)])

In [71]:
a

array([[1, 3, 5],
       [3, 4, 5],
       [2, 8, 7]])

In [72]:
b

array([[6, 3, 9],
       [5, 3, 8],
       [9, 7, 5]])

In [75]:
np.vstack((a,b))

array([[1, 3, 5],
       [3, 4, 5],
       [2, 8, 7],
       [6, 3, 9],
       [5, 3, 8],
       [9, 7, 5]])

In [76]:
np.hstack((a,b))

array([[1, 3, 5, 6, 3, 9],
       [3, 4, 5, 5, 3, 8],
       [2, 8, 7, 9, 7, 5]])

In [78]:
np.ravel((a,b))

array([1, 3, 5, 3, 4, 5, 2, 8, 7, 6, 3, 9, 5, 3, 8, 9, 7, 5])

In [79]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
for i in np.arange(1,5):
    print(x)

[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]


In [81]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427,  0.6569866 ]])

In [82]:
np.tan(x)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501,  0.87144798]])

In [83]:
np.cos(a)

array([[ 0.54030231, -0.9899925 ,  0.28366219],
       [-0.9899925 , -0.65364362,  0.28366219],
       [-0.41614684, -0.14550003,  0.75390225]])

## pandas

In [84]:
import pandas as pd

In [85]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [86]:
#creating a series data type

In [87]:
s=pd.Series([1,2,3,34,5,56])

In [88]:
s

0     1
1     2
2     3
3    34
4     5
5    56
dtype: int64

In [92]:
s1=pd.Series([1,2,3,34,5,56],index=['x','y','z','a','b','c'])

In [93]:
s1

x     1
y     2
z     3
a    34
b     5
c    56
dtype: int64

In [100]:
s+s1

x      2
y      4
z      6
a     68
b     10
c    112
dtype: int64

In [218]:
v1=[1,2,5,9]
v2=[9,3,4,5]
df=pd.DataFrame({'x':v1,'y':v2})

In [219]:
df

x  y
0  1  9
1  2  3
2  5  4
3  9  5

In [123]:
df.isnull()

x      y
0  False  False
1  False  False
2  False  False
3  False  False

In [130]:
df1=pd.DataFrame({'x':[20,32,34,21],'y':[6,4,3,299]},index=['a','b','c','d'],dtype=float)

In [131]:
df1

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [208]:
data=[[20,32,34,21],[6,4,3,299],[2,3,4]]

In [209]:
df=pd.DataFrame(data,columns=["x1",'x2','x3','x4'])

In [210]:
df

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

In [211]:
df.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False  False
2  False  False  False   True

In [212]:
df.values

array([[ 20.,  32.,  34.,  21.],
       [  6.,   4.,   3., 299.],
       [  2.,   3.,   4.,  nan]])

In [213]:
df.size

12

In [214]:
df.shape

(3, 4)

In [215]:
df.ndim

2

In [216]:
#slicing

In [217]:
df

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

In [168]:
df.head()

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

In [169]:
df.tail(2)

x1  x2  x3     x4
1   6   4   3  299.0
2   2   3   4    NaN

In [170]:
df.tail(1)

x1  x2  x3  x4
2   2   3   4 NaN

In [171]:
df.tail()

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

In [172]:
#merging and joning 

In [176]:
df1

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [187]:
df

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [199]:
data=[[2,3,4],[2,6,7,8],[3,2,45,7]]
df1=pd.DataFrame(data,columns=["x1",'x2','x3','x4'])

In [200]:
df1

x1  x2  x3   x4
0   2   3   4  NaN
1   2   6   7  8.0
2   3   2  45  7.0

In [201]:
df

x1  x2  x3     x4
0  20  32  34   21.0
1   6   4   3  299.0
2   2   3   4    NaN

In [202]:
m=pd.merge(df1,df)

In [203]:
print(m)

   x1  x2  x3  x4
0   2   3   4 NaN


In [204]:
m

x1  x2  x3  x4
0   2   3   4 NaN

In [220]:
j=df1.join(df)#,index=["x1",'x2','x3','x4'])

In [222]:
df

x  y
0  1  9
1  2  3
2  5  4
3  9  5

In [223]:
df1

x1  x2  x3   x4
0   2   3   4  NaN
1   2   6   7  8.0
2   3   2  45  7.0

In [224]:
j

x1  x2  x3   x4  x  y
0   2   3   4  NaN  1  9
1   2   6   7  8.0  2  3
2   3   2  45  7.0  5  4

In [225]:
d=[[2,3,4],[4,5,6,7],[5,4,3],[7,8,9,10]]

In [226]:
f1=pd.DataFrame(d,columns=["x",'y','z','z1'],index=[1,2,3,4])

In [227]:
f1

x  y  z    z1
1  2  3  4   NaN
2  4  5  6   7.0
3  5  4  3   NaN
4  7  8  9  10.0

In [233]:
d1=[[3,4,6],[6,7,8,9],[7,8,9,10]]
f2=pd.DataFrame(d1,columns=['x','y','z','z1'])
f2

x  y  z    z1
0  3  4  6   NaN
1  6  7  8   9.0
2  7  8  9  10.0

In [234]:
merge=pd.merge(f1,f2)

In [235]:
merge

x  y  z    z1
0  7  8  9  10.0

In [237]:
x=[[1,2,3],[4,5,6]]
f3=pd.DataFrame(x,columns=['y1','y2','y3'],index=['a','b'])

In [238]:
f3

y1  y2  y3
a   1   2   3
b   4   5   6

In [240]:
f4=pd.DataFrame({'name':[6,4,11],'genedr':[1,0,1]})
f4

name  genedr
0     6       1
1     4       0
2    11       1

In [242]:
joint=f3.join(f4)

In [243]:
joint

y1  y2  y3  name  genedr
a   1   2   3   NaN     NaN
b   4   5   6   NaN     NaN

In [247]:
#concat
c=pd.concat([f3,f2])
c

C:\Users\Public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


x    y   y1   y2   y3    z    z1
a  NaN  NaN  1.0  2.0  3.0  NaN   NaN
b  NaN  NaN  4.0  5.0  6.0  NaN   NaN
0  3.0  4.0  NaN  NaN  NaN  6.0   NaN
1  6.0  7.0  NaN  NaN  NaN  8.0   9.0
2  7.0  8.0  NaN  NaN  NaN  9.0  10.0

In [248]:
c.isnull()

x      y     y1     y2     y3      z     z1
a   True   True  False  False  False   True   True
b   True   True  False  False  False   True   True
0  False  False   True   True   True  False   True
1  False  False   True   True   True  False  False
2  False  False   True   True   True  False  False

In [249]:
c.notnull()

x      y     y1     y2     y3      z     z1
a  False  False   True   True   True  False  False
b  False  False   True   True   True  False  False
0   True   True  False  False  False   True  False
1   True   True  False  False  False   True   True
2   True   True  False  False  False   True   True

In [250]:
c.columns

Index(['x', 'y', 'y1', 'y2', 'y3', 'z', 'z1'], dtype='object')

In [251]:
c["y2"]

a    2.0
b    5.0
0    NaN
1    NaN
2    NaN
Name: y2, dtype: float64

In [257]:
#index changing
c1=pd.DataFrame({1:[1,2,3],2:[4,5,6],'i':['x','y','z']})
c1.set_index('i')

1  2
i      
x  1  4
y  2  5
z  3  6

In [263]:
#changing the coulmn headers
c2=c1.rename(columns={1:'a',2:'b'})
c2

a  b  i
0  1  4  x
1  2  5  y
2  3  6  z

In [262]:
c1

1  2  i
0  1  4  x
1  2  5  y
2  3  6  z

In [264]:
#data munging
dd=pd.read_csv("table.csv")

In [265]:
dd

x  y   z
0  5  0  43
1  3  9   2
2  4  7  88
3  5  6   1

In [266]:
dd['x']

0    5
1    3
2    4
3    5
Name: x, dtype: int64

In [270]:
help(pd.read_json)

Help on function read_json in module pandas.io.json.json:

read_json(path_or_buf=None, orient=None, typ='frame', dtype=True, convert_axes=True, convert_dates=True, keep_default_dates=True, numpy=False, precise_float=False, date_unit=None, encoding=None, lines=False, chunksize=None, compression='infer')
    Convert a JSON string to pandas object.
    
    Parameters
    ----------
    path_or_buf : a valid JSON string or file-like, default: None
        The string could be a URL. Valid URL schemes include http, ftp, s3,
        gcs, and file. For file URLs, a host is expected. For instance, a local
        file could be ``file://localhost/path/to/table.json``
    
    orient : string,
        Indication of expected JSON string format.
        Compatible JSON strings can be produced by ``to_json()`` with a
        corresponding orient value.
        The set of possible orients is:
    
        - ``'split'`` : dict like
          ``{index -> [index], columns -> [columns], data -> [values]