In [1]:
#elements acessings row/column
# loc and iloc--->locatioin and index location based


In [15]:
import pandas  as pd
df=pd.DataFrame({"name":['pinky','pop','push','puppy'],
                 "roll-numbers":[401,403,405,34],
                 "branch":["cse","ece","eee","civill"]},index=[1,2,3,4])

In [16]:
df

name  roll-numbers  branch
1  pinky           401     cse
2    pop           403     ece
3   push           405     eee
4  puppy            34  civill

In [21]:
df.loc[4]

name             puppy
roll-numbers        34
branch          civill
Name: 4, dtype: object

In [22]:
df.loc[2]['roll-numbers']

403

In [23]:
df.iloc[0]

name            pinky
roll-numbers      401
branch            cse
Name: 1, dtype: object

In [24]:
df.iloc[3]

name             puppy
roll-numbers        34
branch          civill
Name: 4, dtype: object

In [25]:
df.iloc[2]["branch"]

'eee'

In [26]:
df

name  roll-numbers  branch
1  pinky           401     cse
2    pop           403     ece
3   push           405     eee
4  puppy            34  civill

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name            4 non-null object
roll-numbers    4 non-null int64
branch          4 non-null object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes


In [28]:
df.describe()

roll-numbers
count      4.000000
mean     310.750000
std      184.507227
min       34.000000
25%      309.250000
50%      402.000000
75%      403.500000
max      405.000000

In [29]:
df.count()

name            4
roll-numbers    4
branch          4
dtype: int64

In [30]:
df.dtypes

name            object
roll-numbers     int64
branch          object
dtype: object

In [31]:
df.count(axis='rows')

name            4
roll-numbers    4
branch          4
dtype: int64

In [33]:
df.count(axis=1)

1    3
2    3
3    3
4    3
dtype: int64

In [34]:
df.count(axis='columns')

1    3
2    3
3    3
4    3
dtype: int64

In [35]:
df.count(axis=0)

name            4
roll-numbers    4
branch          4
dtype: int64

In [36]:
df

name  roll-numbers  branch
1  pinky           401     cse
2    pop           403     ece
3   push           405     eee
4  puppy            34  civill

In [39]:
df.set_index(["roll-numbers","branch"])

name
roll-numbers branch       
401          cse     pinky
403          ece       pop
405          eee      push
34           civill  puppy

In [49]:
import numpy as np
frame=pd.Series([2,3,45,56,8])
frame

0     2
1     3
2    45
3    56
4     8
dtype: int64

In [50]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [55]:
print(frame.describe())

count     5.000000
mean     22.800000
std      25.684626
min       2.000000
25%       3.000000
50%       8.000000
75%      45.000000
max      56.000000
dtype: float64


In [54]:
frame.count()

5

In [58]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])

In [72]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [97]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=list('abc'))

In [98]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [99]:
data.loc[1,'b']=np.nan
data

a     b   c
0  0   1.0   2
1  3   NaN   5
2  6   7.0   8
3  9  10.0  11

In [100]:
data.isnull().sum()

a    0
b    1
c    0
dtype: int64

In [101]:
df

name  roll-numbers  branch
1  pinky           401     cse
2    pop           403     ece
3   push           405     eee
4  puppy            34  civill

In [102]:
df+data

a   b branch   c name  roll-numbers
0 NaN NaN    NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN  NaN           NaN
4 NaN NaN    NaN NaN  NaN           NaN

In [106]:
dd=df.add(data)
dd

a   b branch   c name  roll-numbers
0 NaN NaN    NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN  NaN           NaN
4 NaN NaN    NaN NaN  NaN           NaN

In [110]:
dd.add(data,fill_value=9)

a     b branch     c name  roll-numbers
0   9.0  10.0    NaN  11.0  NaN           NaN
1  12.0   NaN    NaN  14.0  NaN           NaN
2  15.0  16.0    NaN  17.0  NaN           NaN
3  18.0  19.0    NaN  20.0  NaN           NaN
4   NaN   NaN    NaN   NaN  NaN           NaN

In [114]:
np.random.randn(2,5)

array([[ 0.86044482, -0.02134572,  1.0656732 ,  0.52411881, -1.38750972],
       [-0.64640164, -0.94997909,  0.53171474, -1.58586374, -1.4068182 ]])

In [115]:
np.random.rand(1,10)

array([[0.19635029, 0.32691801, 0.02639281, 0.89823052, 0.93842621,
        0.28086101, 0.86048444, 0.22973116, 0.21012471, 0.31790009]])

In [118]:
#creating dataframe with random values
r=pd.DataFrame(np.random.randn(3,4),index=['c','b','a'],
               columns=['s1','s2','s3','s4'])
r

s1        s2        s3        s4
c -0.824800  1.817316  0.897535  1.585518
b  0.237804 -0.326782 -0.247983 -0.061048
a -0.181943  1.022917  0.948163 -0.206890

In [123]:
r.index=['c','b','a']

In [124]:
r

s1        s2        s3        s4
c -0.824800  1.817316  0.897535  1.585518
b  0.237804 -0.326782 -0.247983 -0.061048
a -0.181943  1.022917  0.948163 -0.206890

In [126]:
#reindexing
r1=r.reindex(['a','b','c','d'])
r1

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d       NaN       NaN       NaN       NaN

In [127]:
r1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [128]:
r1.dropna()#dropping the null values

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518

In [130]:
r1.fillna(3)#filling null values

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d  3.000000  3.000000  3.000000  3.000000

In [134]:
r1.fillna(method='bfill',axis=0).fillna(1)#backward filling

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d  1.000000  1.000000  1.000000  1.000000

In [135]:
r1.fillna(method='ffill',axis=0).fillna(1)#forward fill

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d -0.824800  1.817316  0.897535  1.585518

In [136]:
r1.isna()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [137]:
r1.isnull()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [151]:
pd.isna(r1['s4'])

a    False
b    False
c    False
d     True
Name: s4, dtype: bool

In [152]:
#data replacing
r1

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d       NaN       NaN       NaN       NaN

In [155]:
df33=pd.DataFrame({11:[4,5,6],12:[34,5,6],13:[2,7,8]})
df33

11  12  13
0   4  34   2
1   5   5   7
2   6   6   8

In [156]:
df33.replace(4,9999)

11  12  13
0  9999  34   2
1     5   5   7
2     6   6   8

In [159]:
df33.replace([34,2,6],[111,222,333])

11   12   13
0    4  111  222
1    5    5    7
2  333  333    8

In [160]:
df33.replace({4:40,8:55})

11  12  13
0  40  34   2
1   5   5   7
2   6   6  55

In [168]:
#index sorting and ranking
r2=r1.reindex(['a','c','b','e'])
r2
#r1

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
c -0.824800  1.817316  0.897535  1.585518
b  0.237804 -0.326782 -0.247983 -0.061048
e       NaN       NaN       NaN       NaN

In [169]:
r2.sort_index()

s1        s2        s3        s4
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
e       NaN       NaN       NaN       NaN

In [171]:
r1.columns=['s4','s2','s1','s5']
r1

s4        s2        s1        s5
a -0.181943  1.022917  0.948163 -0.206890
b  0.237804 -0.326782 -0.247983 -0.061048
c -0.824800  1.817316  0.897535  1.585518
d       NaN       NaN       NaN       NaN

In [173]:
r1.sort_index(axis=1)

s1        s2        s4        s5
a  0.948163  1.022917 -0.181943 -0.206890
b -0.247983 -0.326782  0.237804 -0.061048
c  0.897535  1.817316 -0.824800  1.585518
d       NaN       NaN       NaN       NaN

In [175]:
#groupby 
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                        'place':['zoo','ooo','zoo','oo','oo'],
                        'feature':['s','s','s','p','q']})
animal_df

name place feature
0  dog   zoo       s
1  cat   ooo       s
2  cow   zoo       s
3  dog    oo       p
4  cat    oo       q

In [176]:
animal_df.groupby('name')

In [178]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [179]:
animal_df.groupby('name').sum()

place feature
name               
cat   ooooo      sq
cow     zoo       s
dog   zoooo      sp

In [181]:
animal_df.groupby(['name','feature']).sum()

place
name feature      
cat  q          oo
     s         ooo
cow  s         zoo
dog  p          oo
     s         zoo

In [184]:
animal_df.groupby(['feature']).sum()

name      place
feature                      
p              dog         oo
q              cat         oo
s        dogcatcow  zooooozoo

In [199]:
#Ranking
ani_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                        'place':['zoo','ooo','zoo','oo','oo'],
                        'no-legs':[4,2,3,2,np.nan]})

In [200]:
ani_df

name place  no-legs
0  dog   zoo      4.0
1  cat   ooo      2.0
2  cow   zoo      3.0
3  dog    oo      2.0
4  cat    oo      NaN

In [201]:
ani_df["rank1"]=ani_df['no-legs'].rank()
ani_df

name place  no-legs  rank1
0  dog   zoo      4.0    4.0
1  cat   ooo      2.0    1.5
2  cow   zoo      3.0    3.0
3  dog    oo      2.0    1.5
4  cat    oo      NaN    NaN

In [202]:
ani_df["max-rank"]=ani_df['no-legs'].rank(method="max")
ani_df

name place  no-legs  rank1  max-rank
0  dog   zoo      4.0    4.0       4.0
1  cat   ooo      2.0    1.5       2.0
2  cow   zoo      3.0    3.0       3.0
3  dog    oo      2.0    1.5       2.0
4  cat    oo      NaN    NaN       NaN

In [203]:
ani_df["first-rank"]=ani_df['no-legs'].rank(method="first")
ani_df

name place  no-legs  rank1  max-rank  first-rank
0  dog   zoo      4.0    4.0       4.0         4.0
1  cat   ooo      2.0    1.5       2.0         1.0
2  cow   zoo      3.0    3.0       3.0         3.0
3  dog    oo      2.0    1.5       2.0         2.0
4  cat    oo      NaN    NaN       NaN         NaN

In [204]:
ani_df["non-rank"]=ani_df['no-legs'].rank(na_option="bottom")
ani_df

name place  no-legs  rank1  max-rank  first-rank  non-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0
1  cat   ooo      2.0    1.5       2.0         1.0       1.5
2  cow   zoo      3.0    3.0       3.0         3.0       3.0
3  dog    oo      2.0    1.5       2.0         2.0       1.5
4  cat    oo      NaN    NaN       NaN         NaN       5.0

In [205]:
ani_df["pct-rank"]=ani_df['no-legs'].rank(pct=True)
ani_df

name place  no-legs  rank1  max-rank  first-rank  non-rank  pct-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0     1.000
1  cat   ooo      2.0    1.5       2.0         1.0       1.5     0.375
2  cow   zoo      3.0    3.0       3.0         3.0       3.0     0.750
3  dog    oo      2.0    1.5       2.0         2.0       1.5     0.375
4  cat    oo      NaN    NaN       NaN         NaN       5.0       NaN

In [211]:
#categorise
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [212]:
data_frame["cc"]=data_frame['y'].astype('category')

In [213]:
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [214]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [216]:
data_frame["cc"].cat.categories=["good","bad","worst",
                                 "verybad",'verygood']
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [228]:
data_frame["cc"]=data_frame["cc"].set_categories=["good","bad","worst",
                                 "verybad",'verygood']
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [229]:
data_frame.sort_values('cc')

x   y        cc
1  2   7       bad
0  1   6      good
3  4   9   verybad
4  5  10  verygood
2  3   8     worst

In [231]:
data_frame.groupby("cc").size()

cc
bad         1
good        1
verybad     1
verygood    1
worst       1
dtype: int64

In [232]:
#reading data
df=pd.read_table("sample.txt")
df

C:\Users\Public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


a b c
0  1 2 3
1  3 4 5
2  4 5 6

In [237]:
df=pd.read_table("ex1.csv")
df

C:\Users\Public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [238]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\Public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [241]:
df=pd.read_csv("ex2.csv")
df

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [242]:
df.head(1)

1  2  3  4  hello
0  5  6  7  8  world

In [243]:
df.tail(1)

1   2   3   4 hello
1  9  10  11  12   foo