### Ensemble Models

In [1]:
# Ensemble=Collection of multiples

# Voting Classifier

In [2]:
from sklearn.datasets import load_iris

In [3]:
df=load_iris()

In [5]:
#df

In [10]:
df.feature_names
df.data
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
import pandas as pd
df_data=pd.DataFrame(df.data,columns=df.feature_names)
df_data["flower"]=df.target
df_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
x=df_data.iloc[:,0:4].values

In [20]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
y=df.target

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
#training testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,
                                               random_state=1)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [32]:
l_clf=LogisticRegression()
r_clf=RandomForestClassifier()
g_clf=GaussianNB()


In [35]:
v_clf=VotingClassifier(estimators=[("lr",l_clf),("rf",r_clf),
                                   ("gb",g_clf)])

In [37]:
#v_clf

In [38]:
v_clf.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     class_weight=None,
                                                     criterion='gini',...
                                        

In [39]:
#finding accuracy
  #prdict(test,prediction)
from sklearn.metrics import accuracy_score

In [46]:
for i in (l_clf,r_clf,g_clf,v_clf):
    i.fit(x_train,y_train)
    prediction=i.predict(x_test)
    print(i.__class__.__name__,accuracy_score(y_test,prediction))

LogisticRegression 0.8421052631578947
RandomForestClassifier 0.9736842105263158
GaussianNB 0.9736842105263158
VotingClassifier 0.9736842105263158


C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


# Bagging Classifier

In [47]:
#For only Decisiontree

In [48]:
df=pd.read_csv("diabets.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [57]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [59]:
x=df.drop("Outcome",axis=1)
#x

In [60]:
y=df["Outcome"]

In [68]:
#y

In [69]:
#training testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,
                                               random_state=1)

In [73]:
b_clf=BaggingClassifier(DecisionTreeClassifier(),bootstrap=True,
                        n_estimators=10,oob_score=True)

In [74]:
b_clf

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [75]:
b_clf.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:611: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:616: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [77]:
b_clf.oob_score_

0.7135416666666666

In [78]:
predi=b_clf.predict(x_test)
from sklearn.metrics import accuracy_score

In [79]:
 accuracy_score(y_test,predi)

0.78125

# Adaboost classifier

In [81]:
#predicting the error and boosting the values

In [85]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [86]:
cancer_df=load_breast_cancer()

In [88]:
cancer_df

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [89]:
#x,y
x=pd.DataFrame(cancer_df.data,columns=cancer_df.feature_names)

In [91]:
#x
y=pd.Categorical.from_codes(cancer_df.target,cancer_df.target_names)

In [94]:
y

[malignant, malignant, malignant, malignant, malignant, ..., malignant, malignant, malignant, malignant, benign]
Length: 569
Categories (2, object): [malignant, benign]

In [98]:
encoder=LabelEncoder()
binary_y=pd.Series(encoder.fit_transform(y))
binary_y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     0
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
539    0
540    0
541    0
542    0
543    0
544    0
545    0
546    0
547    0
548    0
549    0
550    0
551    0
552    0
553    0
554    0
555    0
556    0
557    0
558    0
559    0
560    0
561    0
562    1
563    1
564    1
565    1
566    1
567    1
568    0
Length: 569, dtype: int32

In [99]:
#training testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,binary_y,test_size=0.25,
                                               random_state=1)

In [101]:
ad_clf=AdaBoostClassifier(DecisionTreeClassifier(max_depth=2),
                          n_estimators=20)

In [103]:
ad_clf.fit(x_train,y_train)
##SAMME.R - Stagewise Additive Modelling using a 
           #multiclass Exponential Loss function Real

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=2,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                             

In [106]:
prediction=ad_clf.predict(x_test)

In [107]:
accuracy_score(y_test,prediction)

0.9300699300699301

In [108]:
from sklearn.metrics import confusion_matrix

In [109]:
confusion_matrix(y_test,prediction)

array([[85,  3],
       [ 7, 48]], dtype=int64)

# GradientBoostingClassifier

In [114]:
import sklearn.datasets

In [115]:
dir(sklearn.datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_svmlight_format',
 'base',
 'california_housing',
 'clear_data_home',
 'covtype',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_mldata',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'kddcup99',
 'lfw',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_ran

In [137]:
train_df=pd.read_csv("train.csv")
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [138]:
test_df=pd.read_csv("test.csv")
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [139]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier

In [140]:
y_train=train_df["Survived"]
#y_train

In [141]:
train_df.drop(labels="Survived",axis=1,inplace=True)

In [142]:
full_df=train_df.append(test_df)
#full_df.head()

In [143]:
drop_columns=["Name","Age","SibSp","Ticket","Cabin","Parch","Embarked"]

In [144]:
full_df.drop(labels=drop_columns,axis=1,inplace=True)

In [145]:
full_df.tail()

PassengerId  Pclass     Sex      Fare
413         1305       3    male    8.0500
414         1306       1  female  108.9000
415         1307       3    male    7.2500
416         1308       3    male    8.0500
417         1309       3    male   22.3583

In [146]:
#creating dummies for female and male
full_df=pd.get_dummies(full_df,columns=["Sex"])
full_df

PassengerId  Pclass      Fare  Sex_female  Sex_male
0              1       3    7.2500           0         1
1              2       1   71.2833           1         0
2              3       3    7.9250           1         0
3              4       1   53.1000           1         0
4              5       3    8.0500           0         1
5              6       3    8.4583           0         1
6              7       1   51.8625           0         1
7              8       3   21.0750           0         1
8              9       3   11.1333           1         0
9             10       2   30.0708           1         0
10            11       3   16.7000           1         0
11            12       1   26.5500           1         0
12            13       3    8.0500           0         1
13            14       3   31.2750           0         1
14            15       3    7.8542           1         0
15            16       2   16.0000           1         0
16            17       3   29.1250           0         1
17            18       2   13.0000           0         1
18            19       3   18.0000           1         0
19            20       3    7.2250           1         0
20            21       2   26.0000           0         1
21            22       2   13.0000           0         1
22            23       3    8.0292           1         0
23            24       1   35.5000           0         1
24            25       3   21.0750           1         0
25            26       3   31.3875           1         0
26            27       3    7.2250           0         1
27            28       1  263.0000           0         1
28            29       3    7.8792           1         0
29            30       3    7.8958           0         1
..           ...     ...       ...         ...       ...
388         1280       3    7.7500           0         1
389         1281       3   21.0750           0         1
390         1282       1   93.5000           0         1
391         1283       1   39.4000           1         0
392         1284       3   20.2500           0         1
393         1285       2   10.5000           0         1
394         1286       3   22.0250           0         1
395         1287       1   60.0000           1         0
396         1288       3    7.2500           0         1
397         1289       1   79.2000           1         0
398         1290       3    7.7750           0         1
399         1291       3    7.7333           0         1
400         1292       1  164.8667           1         0
401         1293       2   21.0000           0         1
402         1294       1   59.4000           1         0
403         1295       1   47.1000           0         1
404         1296       1   27.7208           0         1
405         1297       2   13.8625           0         1
406         1298       2   10.5000           0         1
407         1299       1  211.5000           0         1
408         1300       3    7.7208           1         0
409         1301       3   13.7750           1         0
410         1302       3    7.7500           1         0
411         1303       1   90.0000           1         0
412         1304       3    7.7750           1         0
413         1305       3    8.0500           0         1
414         1306       1  108.9000           1         0
415         1307       3    7.2500           0         1
416         1308       3    8.0500           0         1
417         1309       3   22.3583           0         1

[1309 rows x 5 columns]

In [147]:
full_df.isnull().sum()

PassengerId    0
Pclass         0
Fare           1
Sex_female     0
Sex_male       0
dtype: int64

In [148]:
full_df.fillna(value=0.0,inplace=True)

In [149]:
full_df.isnull().sum()

PassengerId    0
Pclass         0
Fare           0
Sex_female     0
Sex_male       0
dtype: int64

In [159]:
x_train=full_df.values[0:891]
#x=full_df.iloc[:,0:4].values
print(x_train)
x_test=full_df.values[891:]
print(x_test)

[[  1.       3.       7.25     0.       1.    ]
 [  2.       1.      71.2833   1.       0.    ]
 [  3.       3.       7.925    1.       0.    ]
 ...
 [889.       3.      23.45     1.       0.    ]
 [890.       1.      30.       0.       1.    ]
 [891.       3.       7.75     0.       1.    ]]
[[8.92000e+02 3.00000e+00 7.82920e+00 0.00000e+00 1.00000e+00]
 [8.93000e+02 3.00000e+00 7.00000e+00 1.00000e+00 0.00000e+00]
 [8.94000e+02 2.00000e+00 9.68750e+00 0.00000e+00 1.00000e+00]
 ...
 [1.30700e+03 3.00000e+00 7.25000e+00 0.00000e+00 1.00000e+00]
 [1.30800e+03 3.00000e+00 8.05000e+00 0.00000e+00 1.00000e+00]
 [1.30900e+03 3.00000e+00 2.23583e+01 0.00000e+00 1.00000e+00]]


In [160]:
# feature scalling
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [161]:
#training testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train,
                        test_size=0.25,random_state=1)

In [172]:
#learning rates
lr=[0.05,0.075,0.1,0.25,0.75,1]
for i in lr:
    gb_clf=GradientBoostingClassifier(n_estimators=20,
                                      learning_rate=i,max_features=2)
    gb_clf.fit(x_train,y_train)
    print("learning Rate",i)
    print("Accuracy score in TRaning:{0:.3f}".format(gb_clf.score(x_train,y_train)))
    print("Accuracy score in Testing:{0:.3f}".format(gb_clf.score(x_train,y_train)))
    

learning Rate 0.05
Accuracy score in TRaning:0.828
Accuracy score in Testing:0.828
learning Rate 0.075
Accuracy score in TRaning:0.831
Accuracy score in Testing:0.831
learning Rate 0.1
Accuracy score in TRaning:0.825
Accuracy score in Testing:0.825
learning Rate 0.25
Accuracy score in TRaning:0.841
Accuracy score in Testing:0.841
learning Rate 0.75
Accuracy score in TRaning:0.898
Accuracy score in Testing:0.898
learning Rate 1
Accuracy score in TRaning:0.895
Accuracy score in Testing:0.895


In [175]:
gb_clf=GradientBoostingClassifier(n_estimators=20,
                    learning_rate=0.5,max_depth=2,max_features=2)

In [176]:
gb_clf.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.5, loss='deviance', max_depth=2,
                           max_features=2, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [177]:
predi=gb_clf.predict(x_test)

In [178]:
confusion_matrix(y_test,predi)

array([[119,   9],
       [ 36,  59]], dtype=int64)

In [182]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predi))

              precision    recall  f1-score   support

           0       0.77      0.93      0.84       128
           1       0.87      0.62      0.72        95

    accuracy                           0.80       223
   macro avg       0.82      0.78      0.78       223
weighted avg       0.81      0.80      0.79       223

